### ISSUE TITLE
Kubeflow_periodic prow job is always failing

### ISSUE THREAD

**Issue by richardsliu** [kubeflow/testing#214]
https://prow.k8s.io/?type=periodic&job=kubeflow-periodic

**Comment by jlewi** [comment]
Here's the prow log

```
+ /usr/local/bin/checkout.sh /src
+ SRC_DIR=/src
+ mkdir -p /src/
+ git clone https://github.com//.git /src//
Cloning into '/src'...
fatal: could not read Username for 'https://github.com': No such device or address
```
So it looks like the problem is in the case of a periodic job; the environment variables that our checkout.sh script depends on aren't set so we don't end up cloning the repo properly.

See here:
https://github.com/kubernetes/test-infra/tree/master/prow

checkout.sh should probably detect if its a periodic job and if it is I think we'll need to use the JOB_NAME to determine which repo and tests to run.
