### ISSUE TITLE
E2E test should recycle long running workflows

### ISSUE THREAD

**Issue by kunmingg** [kubeflow/testing#275]
Due to various reasons, some workflows refuse to exit after error happened.
This could hold resources and block other tests.
We should have a cronjob which delete workflows with life > 4 hours.

**Comment by jlewi** [comment]
This is our cleanup script:
https://github.com/kubeflow/testing/blob/master/py/kubeflow/testing/cleanup_ci.py

@kunmingg Were pods left running?

Do we need to GC the workflows or is it sufficient to GC the pods?

We want to leave the workflows around for say 7 days because its helpful for debugging.

so it would be good to understand 

1. Is the workflow in a terminal state; e.g. failed
1. If the workflow is not in a terminal state how can we force it to terminate 

   * Or at least to stop hogging resources; e.g. if delete all its pods would that work?

**Comment by kunmingg** [comment]
pods were on ```pending creation```. (Already grab some resources, depends on their detailed status).
So GC pods is insufficient as workflows will recreate them and pending again. 

Can we set max workflow life = 12 hours? Should be enough for debugging and avoid holding resources too long.

**Comment by richardsliu** [comment]
Potential symptoms of this bug - tests can fail with errors like:
```
failed to create fsnotify watcher: too many open files
```
and/or
```
failed to save outputs: verify serviceaccount kubeflow-test-infra:default has necessary privileges
```

**Comment by jlewi** [comment]
Does Argo provide a way to impose a max lifetime on Workflows or individual steps?

I think if we aggressively garbage collect Argo workflows its going to make troubleshooting test failures really difficult.

/cc @jessesuen

**Comment by richardsliu** [comment]
Do we still need this?

**Comment by richardsliu** [comment]
Reopen.

**Comment by jlewi** [comment]
Downgrading this to P2
