### ISSUE TITLE
A more sustainable approach to owning and maintaining test/release infrastructure

### ISSUE THREAD

**Issue by jlewi** [kubeflow/testing#737]
We need a more sustainable and scalable approach to owning and maintaining engprod(test & release) infrastructure for kubeflow.

We currently lack a sufficient number of individuals (3-5?) with the willingness and ability (e.g. time) to meet the increasing demands of Kubeflow as it grows.

I think there are a couple of problems we need to address

* How do we drive larger engprod projects that would make our infrastructure more scalable?
  * e.g. Using GitOps to make it easier for anyone to submit changes to the infra
  * Automation of publishing release artifacts
* How do we staff a build cop rotation so that developers aren't blocked for long periods when there are operational problems?

I don't think we can address this by. simply  increasing the pool of "20%" contributors to engprod.

* Its hard to be a good leader in your 20% time
  * We need folks who can identify problems, propose solutions, and drive those solutions to completion
  * This is tough to do if your just working on a project 20% of the time.

* For security reasons, we can't grant an increasing number of individuals the elevated permissions needed to maintain the test/release infrastructure

* Engprod operational issues are often P0 because they block everyone from getting work done; we can't expect 20% contributors to drop everything in order to respond to P0s.

I can think of two approaches to this

1. We try to staff a horizontal team supporting enprod across Kubeflow
1. We can make each WG responsible for its own test/release infrastructure

@cliveseldon @yuzisun @ellistarn @neuromage @paveldournov @elikatsis @vpavlin @yanniszark @Jeffwan @krishnadurai @terrytangyuan @gaocegege @andreyvelich @johnugeorge @aronchick @StefanoFioravanzo @elviraux @kimwnasptd @krazyhaas @jinchihe  @animeshsingh

**Comment by 8bitmp3** [comment]
+1. Bumping this discussion @jlewi

**Comment by swiftdiaries** [comment]
I have a suggestion on this. I think there's 3 levels of testing in Kubeflow.
- Native tests (unit and integration tests that run natively on a machine)
- Application tests (KFServing, Jupyter-Web-App etc...)
- E2E tests (platform level tests)

The Native tests and Application tests probably need to be nimble and fast. I was thinking we could use GitHub Actions for this. This would kind of free-up testing resources and unblock application owners from delving deep into the Prow/k8s test infra space (because that is a lot of cognitive load).

The E2E tests can be owned by the platform owners with each of them bringing their own environments and staffing it themselves. So currently, we have:
- GCP
- IBM
- AWS
- vanilla k8s (or onpremise)

@Jeffwan probably has the right idea with https://github.com/kubeflow/testing/issues/748. Istio has a similar setup with IBM having separate testing environment and so on... This might solve issues around permissions and also unblock application owners to think about testing their applications independently.

What do people think?

/cc @jlewi @animeshsingh @Jeffwan @8bitmp3

**Comment by jlewi** [comment]
@swiftdiaries With GitHub actions how are they administered? Would individual projects be able to administer GitHub actions for themselves or would there be a maintenance cost for GitHub org admins?

**Comment by swiftdiaries** [comment]
They can manage it themselves at the repo level

**Comment by yanniszark** [comment]
@swiftdiaries I agree that Github Actions are a great asset and much easier to figure out and get started than the current Prow setup. It would be a great option to enable application developers to quickly develop testing pipelines for their code.
Plus, developers can benefit from a multitude of community-developed actions.

**Comment by Jeffwan** [comment]
I am not sure if all applications owners like to setup testing pipelines by themselves. I assume some engineers them just want to write test cases and roll out to a cluster which can quickly pick tests up. We probably need to cover this cases as well.

**Comment by thesuperzapper** [comment]
+1 on the GitHub actions for everything but the end-to-end testing/CICD.

**Comment by jlewi** [comment]
Related issue buildcop: kubeflow/testing#658

**Comment by jlewi** [comment]
@kubeflow/automl-leads @kubeflow/kfserving-owners @kubeflow/training-leads thoughts?

**Comment by gaocegege** [comment]
cc @kubeflow/wg-automl-leads @kubeflow/wg-training-leads 

> I am not sure if all applications owners like to setup testing pipelines by themselves. I assume some engineers them just want to write test cases and roll out to a cluster which can quickly pick tests up. We probably need to cover this cases as well.


Same idea with @Jeffwan

**Comment by jlewi** [comment]
Related issue to move Kubeflow to the Google instance off prow and stop using Kubernetes.
https://github.com/kubernetes/test-infra/issues/14343

**Comment by Jeffwan** [comment]
I add a doc for community member to review.  This provides an alternative option to run e2e tests on AWS

http://bit.ly/kubeflow-test-infra-aws
