### ISSUE TITLE
Upgrade the tekton version in kf-ci-v1

### ISSUE THREAD

**Issue by jinchihe** [kubeflow/testing#746]
Seem the tekton is installed in kf-ci-v1, but the version is `v1alpha1`, shall we upgrade the version to `v1beta1`?

**Comment by jinchihe** [comment]
@jlewi I did not get any tekton info under https://github.com/kubeflow/testing/tree/master/test-infra/kf-ci-v1   
Is that installed manually? May I upgrade tekton to v1beta1? thanks.

**Comment by jlewi** [comment]
@jinchihe Yeah I just installed it manuallykubeflow/testing/issues/424 is the issue although there isn't much info there.

Upgrading Tekton on kf-ci-v1 is one option but I'd like to propose a slightly more expensive but better option.

Right now we have two CI clusters

* kubeflow-testing
* kubeflow-ci-v1

It would be beneficial to consolidate down to a single cluster. It probably makes sense to stick with kubeflow-testing because that is where prow is configured to launch prow pods and moving prow is probably a headache.

Before we can install Tekton on kubeflow-testing we need to upgrade it; it is still on K8s 1.14. I think what we want to do is

1. Upgrade the master to 1.15 and then 1.16
1. Enroll the cluster in the [regular channel](https://cloud.google.com/kubernetes-engine/docs/release-notes-regular)
1. Install Tekton in kubeflow-testing
1. Migrate tekton workflows from kubeflow-ci-v1 to kubeflow-testing

/cc @Bobgy

**Comment by Bobgy** [comment]
The plan sounds good to me
