### ISSUE TITLE
Add e2e testing on OpenShift

### ISSUE THREAD

**Issue by tmckayus** [kubeflow/testing#78]
The ultimate goal would be to have Argo able to run multiple testing workflows on different platforms.

A first step would be a setup that can be used to run the e2e tests locally on an OpenShift cluster.

**Comment by jlewi** [comment]
@tmckayus You might want to take a look at kubeflow/kubeflow#473

That PR added minikube support to our E2E tests. This works is follows

1. One step in the workflow deploys minikube (in this case by creating and deploying it on a GCE VM)
2. We store on our NFS share a .kube/config file suitable for configuring kubectl / kubernetes API to talk to the K8s cluster deployed on minikube
3. Subsequent steps in the pipeline just use .kube/config to configure kubectl/ksonnet/python API as needed to talk to the K8s cluster
4. A final minikube specific step tearsdown the minikube VM.

So I think adding OpenShift support largely entails

1. How do you want to deploy an OpenShift cluster?
    - Note for GKE we don't create a new GKE cluster for each E2E test (this is rather slow) we just create a namespace
   - This isn't perfect because certain resources are cluster scoped (e.g. the CRD) 

1. How do you connect to your openshift cluster?

/cc @mhausenblas

**Comment by pdmack** [comment]
I believe this would likely make use of [minishift](https://github.com/minishift/minishift) as opposed to the other "quick" alternative, `oc cluster up`. The latter depends on docker being appropriately configured for insecure registry.

In this regard it would be almost identical to the minikube e2e setup.
